[package]
name = "wasm_executor"
description = "Wasmer execution environment wrapper for the Fluence network"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
keywords = ["fluence", "webassembly", "wasmer"]
license = "Apache-2.0"
maintenance = { status = "actively-developed" }

[lib]
name = "wasm_executor"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "wasm_executor_bin"
path = "src/main.rs"

[dependencies]
wasmer-runtime = "0.6.0"
jni = "0.13.1"
failure = "0.1.5"
lazy_static = "1.4.0"
