[package]
name = "Frank"
description = "Virtual machine based on Wasmer for the Fluence network"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
keywords = ["fluence", "webassembly", "wasmer", "execution environment"]
license = "Apache-2.0"
maintenance = { status = "actively-developed" }

[lib]
name = "frank"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "frank"
path = "src/main.rs"

[dependencies]
wasmer-runtime = "0.6.0"
jni = "0.13.1"
failure = "0.1.5"
lazy_static = "1.4.0"
pwasm-utils = "0.11.0"
parity-wasm = "0.40.2"
sha2 = "0.8.0"
